# Generated by Django 4.0 on 2022-08-25 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookreview', '0001_initial'),
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='loved_by',
            field=models.ManyToManyField(related_name='loved_bookreviews', to='reader.Reader'),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.reader'),
        ),
    ]
