# Generated by Django 4.0.6 on 2022-07-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_alter_reader_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reader',
            name='photo_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
