# Generated by Django 4.0 on 2022-08-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reader',
            old_name='points',
            new_name='reputation',
        ),
    ]
