# Generated by Django 4.0 on 2022-08-28 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_id', models.BigIntegerField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('notification_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_from_me', to='auth.user')),
                ('notification_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_to_me', to='auth.user')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
