# Generated by Django 4.0 on 2022-08-30 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='event_id',
            new_name='event',
        ),
    ]
