# Generated by Django 4.1 on 2022-08-07 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("library", "0001_initial"),
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryStock",
            fields=[
                ("lsid", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField(default=0)),
                ("borrow_fee_per_day", models.IntegerField(default=0)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="book.book"
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library.library",
                    ),
                ),
            ],
            options={"db_table": "library_stock",},
        ),
    ]
