# Generated by Django 4.0.6 on 2022-07-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reader', '0003_alter_reader_bio_alter_reader_photo_url'),
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo_url', models.CharField(max_length=255)),
                ('page_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authors', models.ManyToManyField(to='reader.reader')),
                ('genres', models.ManyToManyField(to='genre.genre')),
            ],
        ),
    ]
