# Generated by Django 4.0 on 2022-08-28 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='text',
        ),
    ]
