# Generated by Django 4.0 on 2022-08-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_pending', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'friend',
            },
        ),
    ]
