# Generated by Django 4.0 on 2022-08-28 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('friend', '0001_initial'),
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='friendship_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_from_me', to='reader.reader'),
        ),
        migrations.AddField(
            model_name='friend',
            name='friendship_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_to_me', to='reader.reader'),
        ),
    ]
