# Generated by Django 4.1 on 2022-08-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reader", "0001_initial"),
        ("genre", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "isbn",
                    models.CharField(max_length=13, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("photo_url", models.CharField(max_length=255)),
                ("page_count", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="authored_books", to="reader.reader"
                    ),
                ),
                ("genres", models.ManyToManyField(to="genre.genre")),
            ],
            options={"db_table": "book",},
        ),
    ]
