# Generated by Django 4.0 on 2022-08-28 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0001_initial'),
        ('bookreview', '0002_initial'),
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commented_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_comments', to='reader.reader'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commented_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bookreview.bookreview'),
        ),
        migrations.AddField(
            model_name='comment',
            name='loved_by',
            field=models.ManyToManyField(related_name='loved_comments', to='reader.Reader'),
        ),
    ]
