# Generated by Django 4.1 on 2022-08-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("gid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=60)),
            ],
            options={"db_table": "genre",},
        ),
    ]
